version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: npm
    directory: "/www"
    schedule:
      interval: "daily"
  - package-ecosystem: cargo
    directory: "/ruldap3"
    schedule:
      interval: "daily"
