version: 2
updates:
  - package-ecosystem: pip
    directory: "/requirements"
    schedule:
      interval: "monthly"
    groups:
      py-deps:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/www"
    schedule:
      interval: "monthly"
    groups:
      js-deps:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: "/ruldap3"
    schedule:
      interval: "monthly"
    groups:
      rust-deps:
        patterns:
          - "*"
