[tool.pytest.ini_options]
asyncio_mode = "strict"

[tool.isort]
profile = "black"
# isort doesn't figure this out on its own
# when run from pre-commit.ci, for some reason.
known_first_party = ["sertifikatsok"]

[tool.mypy]
warn_unused_configs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
