[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.ruff]
select = [
    "E",
    "F",
    "PLW",
    "PLE",
    "W",
    "B",
    "UP",
    "DTZ",
    "TRY",
    "C4",
    "I",
    "N",
    "G",
    "PIE",
    "Q",
    "PTH",
    "S",
    "SIM",
]
ignore = ["TRY003", "S101"]
line-length = 100

[tool.ruff.per-file-ignores]
# Lot's of long ldap strings here
"api/tests/test_search.py" = ["E501"]

[tool.ruff.isort]
known-first-party = ["sertifikatsok"]

[tool.mypy]
warn_unused_configs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
