[tool.pytest.ini_options]
asyncio_mode = "auto"
markers = ["apitest: api tests to be run in the docker compose stack"]

[tool.ruff]
lint.select = [
    "E",
    "F",
    "PLW",
    "PLE",
    "W",
    "B",
    "UP",
    "DTZ",
    "TRY",
    "C4",
    "I",
    "N",
    "G",
    "PIE",
    "PTH",
    "S",
    "SIM",
    "RUF",
    "FBT",
]
lint.ignore = ["TRY003", "S101", "W191", "E501"]
target-version = "py312"

[tool.ruff.lint.per-file-ignores]
# Twisted...
"testserver/testserver/**" = ["N802", "N815"]

[tool.ruff.lint.isort]
known-first-party = ["sertifikatsok"]

[tool.mypy]
warn_unused_configs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true

[[tool.mypy.overrides]]
# Twisted/ldaptor not very well typed :/
disallow_untyped_calls = false
module = ["testserver.main"]

[tool.pyright]
venvPath = "."
venv = ".venv"
