from enum import Enum
from types import TracebackType
from typing import Self

class Ruldap3Error(Exception): ...
class IoError(Ruldap3Error): ...
class OpSendError(Ruldap3Error): ...
class ResultRecvError(Ruldap3Error): ...
class IdScrubSendError(Ruldap3Error): ...
class MiscSendError(Ruldap3Error): ...
class TimeoutError(Ruldap3Error): ...
class FilterParsingError(Ruldap3Error): ...
class EndOfStreamError(Ruldap3Error): ...
class UrlParsingError(Ruldap3Error): ...
class LdapResultError(Ruldap3Error): ...
class DecodingUTF8Error(Ruldap3Error): ...

class Scope(Enum):
    BASE = 1
    ONE = 2
    SUB = 3

class SearchEntry:
    dn: str
    attrs: dict[str, list[str]]
    bin_attrs: dict[str, list[list[int]]]

def is_ldap_filter_valid(filtr: str) -> bool: ...
def ldap_escape(lit: str) -> str: ...

class LdapConnection:
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    async def search(
        self,
        base: str,
        scope: Scope,
        filtr: str,
        attrlist: list[str],
        timeout_sec: int,
    ) -> list[SearchEntry]: ...
    @classmethod
    async def connect(cls, ldap_server: str, timeout_sec: int) -> Self: ...
