# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: ["main", "ga_cache"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/bake-action@v4
        with:
          push: false
          load: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
      - name: Start docker stack
        run: docker compose up -d
      - name: Check with mypy
        run: docker compose exec test mypy .
      - name: Test with pytest
        run: docker compose exec test pytest || (docker compose logs sertifikatsok && return 1)
