# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install bonsai dependencies
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libldap2-dev libsasl2-dev gcc
      - name: Install dependencies
        run: |
          cd api
          pipenv sync --dev
      - name: Build ruldap3
        run: |
          cd api
          pipenv run maturin build -m ../ruldap3/Cargo.toml --manylinux off
      - name: Install ruldap3
        run: |
          cd api
          pipenv run pip install ../ruldap3/target/wheels/*
      - name: Check with mypy
        run: |
          cd api
          pipenv run mypy sertifikatsok
      - name: Test with pytest
        run: |
          cd api
          pipenv run pytest
